name: Auto Build Debug APK

on:
  push:
    branches: [ main ]   # setiap ada push ke main, workflow jalan
  workflow_dispatch:

jobs:
  android-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build Debug APK
        run: flutter build apk --debug

      - name: Upload Debug APK (Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Auto Release Debug APK
        uses: softprops/action-gh-release@v1
        with:
          tag_name: auto-debug-${{ github.run_number }}
          name: "Auto Debug Build #${{ github.run_number }}"
          files: build/app/outputs/flutter-apk/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
