name: Build Release APK

on:
  push:
    branches:
      - main   # setiap push ke main workflow akan jalan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.5' # sesuaikan versi kamu

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: main-build-${{ github.run_number }}   # bikin tag otomatis
          name: "Build ${{ github.run_number }}"
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
